microserviceName: "inventory"

# docker image
image:
  repository: playeconomyacr.azurecr.io/play.inventory
  tag: 1.0.4

# Dictionary of Enviroment Variables
envVariables:
  ASPNETCORE_URLS: "http://+:5004"
  ServiceSettings__Authority: https://playeconomy-gateway.westus2.cloudapp.azure.com/identity/svc

resources:
  limits:
    memory: "128Mi"
    cpu: "150m"

# Container specifications
container:
  port: 5004

identityClientId: fdaa91c8-3f99-4ea7-9558-ffe1438316a2
